import { IDataObject, IExecuteFunctions } from 'n8n-workflow';
import { ResourceOperations } from '../../../help/type/IResource';
import { JimengApiClient } from '../../utils/JimengApiClient';

const TextToImage30Operate: ResourceOperations = {
	name: 'Text to Image 3.0',
	value: 'textToImage30',
	description: 'Generate image from text prompt using Jimeng 3.0 model',
	options: [
		{
			displayName: 'Prompt',
			name: 'prompt',
			type: 'string',
			default: '',
			description: 'Text description for image generation (supports Chinese and English, recommended length <= 120 characters, max 800 characters)',
			required: true,
		},
		{
			displayName: 'Width',
			name: 'width',
			type: 'number',
			default: 1328,
			description: 'Image width. Supported range: 512-2048. Common aspect ratios: 21:9, 16:9, 3:2, 4:3, 1:1, 3:4, 2:3, 9:16.',
			typeOptions: {
				minValue: 512,
				maxValue: 2048,
			},
		},
		{
			displayName: 'Height',
			name: 'height',
			type: 'number',
			default: 1328,
			description: 'Image height. Supported range: 512-2048. Common aspect ratios: 21:9, 16:9, 3:2, 4:3, 1:1, 3:4, 2:3, 9:16.',
			typeOptions: {
				minValue: 512,
				maxValue: 2048,
			},
		},
		{
			displayName: 'Use Pre LLM',
			name: 'use_pre_llm',
			type: 'boolean',
			default: true,
			description: 'Whether to enable text expansion for prompt optimization (recommended for short prompts)',
		},
		{
			displayName: 'Seed',
			name: 'seed',
			type: 'number',
			default: -1,
			description: 'Random seed for generation (-1 for random). Same seed with same parameters will generate similar results.',
		},
		{
			displayName: 'Return URL',
			name: 'return_url',
			type: 'boolean',
			default: true,
			description: 'Whether to return image URLs (valid for 24 hours)',
		},
		{
			displayName: 'Watermark Settings',
			name: 'watermark_settings',
			type: 'collection',
			default: {},
			options: [
				{
					displayName: 'Add Watermark',
					name: 'add_logo',
					type: 'boolean',
					default: false,
					description: 'Whether to add watermark to the generated image',
				},
				{
					displayName: 'Custom Text',
					name: 'logo_text_content',
					type: 'string',
					default: '',
					description: 'Custom watermark text content',
				},
				{
					displayName: 'Language',
					name: 'language',
					type: 'options',
					default: 0,
					options: [
						{ name: 'Chinese (AI Generated)', value: 0 },
						{ name: 'English (Generated by AI)', value: 1 },
					],
					description: 'Watermark language',
				},
				{
					displayName: 'Opacity',
					name: 'opacity',
					type: 'number',
					default: 0.3,
					typeOptions: {
						minValue: 0,
						maxValue: 1,
					},
					description: 'Watermark opacity (0-1)',
				},
				{
					displayName: 'Position',
					name: 'position',
					type: 'options',
					default: 0,
					options: [
						{ name: 'Bottom Right', value: 0 },
						{ name: 'Bottom Left', value: 1 },
						{ name: 'Top Left', value: 2 },
						{ name: 'Top Right', value: 3 },
					],
					description: 'Watermark position',
				},
			],
		},
		{
			displayName: 'AIGC Meta Settings',
			name: 'aigc_meta_settings',
			type: 'collection',
			default: {},
			options: [
				{
					displayName: 'Content Producer',
					name: 'content_producer',
					type: 'string',
					default: '',
					description: 'Content generation service ID',
				},
				{
					displayName: 'Producer ID',
					name: 'producer_id',
					type: 'string',
					default: '',
					description: 'Unique ID for this image data from content generation service',
				},
				{
					displayName: 'Content Propagator',
					name: 'content_propagator',
					type: 'string',
					default: '',
					description: 'Content propagation service provider ID',
				},
				{
					displayName: 'Propagate ID',
					name: 'propagate_id',
					type: 'string',
					default: '',
					description: 'Unique ID for this image data from propagation service provider',
				},
			],
		},
	],
	async call(this: IExecuteFunctions, index: number): Promise<IDataObject> {
		const prompt = this.getNodeParameter('prompt', index) as string;
		const width = this.getNodeParameter('width', index) as number;
		const height = this.getNodeParameter('height', index) as number;
		const usePreLlm = this.getNodeParameter('use_pre_llm', index) as boolean;
		const seed = this.getNodeParameter('seed', index) as number;
		const returnUrl = this.getNodeParameter('return_url', index) as boolean;
		const watermarkSettings = this.getNodeParameter('watermark_settings', index) as any;
		const aigcMetaSettings = this.getNodeParameter('aigc_meta_settings', index) as any;
		const credentials = await this.getCredentials('jimengCredentialsApi');

		const client = new JimengApiClient({
			accessKeyId: credentials.accessKeyId as string,
			secretAccessKey: credentials.secretAccessKey as string,
			region: credentials.region as string,
		});

		// Build watermark configuration
		let logoInfo = undefined;
		if (watermarkSettings && Object.keys(watermarkSettings).length > 0) {
			logoInfo = {
				add_logo: watermarkSettings.add_logo || false,
				position: watermarkSettings.position || 0,
				language: watermarkSettings.language || 0,
				opacity: watermarkSettings.opacity || 0.3,
				logo_text_content: watermarkSettings.logo_text_content || '',
			};
		}

		// Build AIGC metadata configuration
		let aigcMeta = undefined;
		if (aigcMetaSettings && Object.keys(aigcMetaSettings).length > 0) {
			aigcMeta = {
				content_producer: aigcMetaSettings.content_producer || '',
				producer_id: aigcMetaSettings.producer_id || '',
				content_propagator: aigcMetaSettings.content_propagator || '',
				propagate_id: aigcMetaSettings.propagate_id || '',
			};
		}

		const data = await client.textToImage30({
			prompt,
			width,
			height,
			use_pre_llm: usePreLlm,
			seed: seed === -1 ? undefined : seed,
			return_url: returnUrl,
			logo_info: logoInfo,
			aigc_meta: aigcMeta,
		});

		return {
			code: data.code,
			message: data.message,
			requestId: data.request_id,
			status: data.status,
			timeElapsed: data.time_elapsed,
			data: {
				taskId: data.data?.task_id,
				status: data.data?.status,
				binaryDataBase64: data.data?.binary_data_base64 || [],
				imageUrls: data.data?.image_urls || [],
			},
		};
	},
};

export default TextToImage30Operate;
